name: CD

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node env
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Generate static files
        run: npm run generate
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./dist
          if-no-files-found: error
  upload-assets:
    name: Upload assets
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./dist
      - name: Zip files
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r ./graph-editor.zip ./dist/
      - name: Release assets
        uses: softprops/action-gh-release@v1
        with:
          files: graph-editor.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./dist
      - name: Create 404.html file
        run: cp ./dist/200.html ./dist/404.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: ./dist
          clean: true
          git-config-name: Jan Müller
          git-config-email: janmueller3698@gmail.com
